const questions = {
    1: {
        title: "내가 행복함을 느끼는 시간대는?",
        type: "lightness",
        A: "./src/images/1_day.jpg",
        A_des: "낮",
        B: "./src/images/1_night.jpg",
        B_des: "밤",
    },
    2: {
        title: "오랜만의 휴식! 어떻게 시간을 보낼까?",
        type: "lightness",
        A: "./src/images/2_summer.jpg",
        A_des: "야외 수영장",
        B: "./src/images/2_fall.jpg",
        B_des: "책과 커피",
    },
    3: {
        title: "바다에 놀러 갔다. 인생샷은 언제?",
        type: "lightness",
        A: "./src/images/3_whitesand.jpg",
        A_des: "낮 시간의 바다",
        B: "./src/images/3_sunset.jpg",
        B_des: "노을 지는 바다",
    },
    4: {
        title: "평소에 좋아하는 옷 스타일은?",
        type: "sharpness",
        A: "./src/images/minimal.jpg",
        A_des: "단정한 미니멀 룩",
        B: "./src/images/casual.jpg",
        B_des: "편안한 캐주얼 룩",
    },
    5: {
        title: "여가 시간을 즐기고 싶은 장소는?",
        type: "sharpness",
        A: "./src/images/5_party.jpg",
        A_des: "친구들과의 파티장",
        B: "./src/images/5_family.jpg",
        B_des: "가족들과의 집",
    },
    6: {
        title: "주말 오후 책을 읽는다면 그 장소는?",
        type: "sharpness",
        A: "./src/images/6_library.jpg",
        A_des: "도서관",
        B: "./src/images/6_hotel.jpg",
        B_des: "침대 위",
    },
    7: {
        title: "산책을 한다면 그 장소는?",
        type: "floral",
        A: "./src/images/7_flowerGarden.jpg",
        A_des: "꽃이 무성한 정원",
        B: "./src/images/7_garden.jpg",
        B_des: "풀과 나무가 무성한 공원",
    },
    8: {
        title: "꽃집에 들어가면 눈에 띄는 것은?",
        type: "floral",
        A: "./src/images/8_floralBouquet.jpg",
        A_des: "풍성한 장미꽃 부케",
        B: "./src/images/8_singleFloral.jpg",
        B_des: "다양한 꽃 몇 송이로 구성된 부케",
    },
    9: {
        title: "커피가 품절이다! 그럼 뭘 마시지?",
        type: "floral",
        A: "./src/images/9_juice.jpg",
        A_des: "달콤한 딸기에이드",
        B: "./src/images/9_lemonade.jpg",
        B_des: "상큼한 레몬에이드",
    },
};

export default questions;
